version: '3'

services:

  go-cache-poc:
    container_name: go-cache-poc
    image: deeptiman1991/go-cache-poc-app:1.0.0
    hostname: kube-go-cache
    build:
        context: .
        dockerfile: Dockerfile    
    environment: 
        GET_HOST_FROM: dns
    networks:
        - go-cache-poc
    volumes: 
        - .:/go/src/go-cache
    ports:
        - 5000:5000
    labels:
      kompose.service.type: LoadBalancer

networks: 
    kube-go-cache:
        driver: bridge


volumes:
  db-data:
