version: '3'

services:

  go-cache-poc:
    container_name: go-cache-kubernetes-container-poc
    image: deeptiman1991/go-cache-kubernetes-v1:1.0.0
    hostname: go-cache-kubernetes-container-poc
    build:
        context: .
        dockerfile: Dockerfile    
    environment: 
        GET_HOST_FROM: dns
    networks:
        - go-cache-poc
    volumes: 
        - .:/go/src/go-cache-kubernetes
    ports:
        - 5000:5000
    labels:
      kompose.service.type: LoadBalancer

networks: 
    go-cache-poc:
        driver: bridge
