apiVersion: v1 
kind: ReplicationController 
metadata:  
  name: kafka-repcon 
  labels:
    app: kafka-repcon 
spec:  
  replicas: 1
  selector:  
    app: kafka 
  template:  
    metadata:  
      labels:  
        app: kafka 
    spec:  
      containers:
        - name: zookeeper-container-app
          image: wurstmeister/kafka 
          command:  
            - /bin/zookeeper-server-start.sh 
            - /config/zookeeper.properties         
          ports:  
            - containerPort: 2181
