apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-app
        role: master
        tier: backend
    spec:
      containers:
      - name: redis-app
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
