apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-service
    role: master
    tier: backend
spec:
  type: LoadBalancer  
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-service
    role: master
    tier: backend
