apiVersion: apps/v1
kind: Deployment
metadata:
  name: redismod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redismod
  template:
    metadata:
      labels:
        app: redismod
    spec:
      containers:
      - name: redismod
        image: redislabs/redismod
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        securityContext:
          capabilities:
            add:
              - SYS_RESOURCE
