apiVersion: v1 
kind: Service 
metadata:  
  name: kafka-service
  labels:
    name: kafka-service
spec:  
  ports:  
    - name: "9092"
      port: 9092 
      targetPort: 9092
      protocol: TCP
    - name: "2181"
      port: 2181 
      targetPort: 2181 
  selector:  
    app: kafka-service 
    type: LoadBalancer
