kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: kafka-ca1
spec:
  type: NodePort
  selector:
    app: kafka-manager
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000