apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: go-cache-kubernetes-pvc-v1-poc
  name: go-cache-kubernetes-pvc-v1-poc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
