apiVersion: v1
kind: Service
metadata:  
  name: go-cache-kubernetes-svc-poc
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: go-cache-kubernetes-app-poc
  type: LoadBalancer
status:
  loadBalancer: {}