apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-cache-kubernetes-app-poc
  labels:
    app: go-cache-kubernetes-app-poc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: go-cache-kubernetes-app-poc
  template:
    metadata:      
      creationTimestamp: null
      labels:
        app: go-cache-kubernetes-app-poc
    spec:
      serviceAccountName: vault
      containers:
      - name: go-cache-kubernetes-container-poc
        image: deeptiman1991/go-cache-kubernetes-v1:1.0.0
        imagePullPolicy: Always
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: JWT_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: SERVICE_PORT
          value: "8080"
        ports:
        - containerPort: 5000          
      hostname: go-cache-kubernetes-app-poc
      restartPolicy: Always
      volumes:
      - name: go-cache-kubernetes-pvc-v1-poc
        persistentVolumeClaim:
          claimName: go-cache-kubernetes-pvc-v1-poc
status: {}