apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: go-cache-poc
  name: go-cache-poc
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: go-cache-poc
    spec:
      containers:
      - env:
        - name: GET_HOST_FROM
          value: dns
        image: deeptiman1991/go-cache-poc:1.0.0
        name: gocachekube
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /go/src/go-cache
          name: go-cache-poc-claim0
      hostname: go-cache-poc
      restartPolicy: Always
      volumes:
      - name: go-cache-poc-claim0
        persistentVolumeClaim:
          claimName: go-cache-poc-claim0
status: {}
