apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-cache-kubernetes-app-poc
  labels:
    app: go-cache-kubernetes-app-poc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: go-cache-kubernetes-app-poc
  template:
    metadata:      
      creationTimestamp: null
      labels:
        app: go-cache-kubernetes-app-poc
    spec:
      containers:
      - name: go-cache-kubernetes-container-poc
        image: deeptiman1991/go-cache-kubernetes-v1:1.0.0
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: password
        ports:
        - containerPort: 5000          
      hostname: go-cache-kubernetes-app-poc
      restartPolicy: Always
      volumes:
      - name: go-cache-kubernetes-pvc-v1-poc
        persistentVolumeClaim:
          claimName: go-cache-kubernetes-pvc-v1-poc
status: {}